# Generated by Django 2.0.7 on 2019-02-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='plantImage',
        ),
        migrations.AddField(
            model_name='plant',
            name='imgURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
