# Generated by Django 2.0.7 on 2019-02-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planting', '0002_auto_20190223_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='imgURL',
            field=models.URLField(blank=True, null=True, verbose_name='ImgURL'),
        ),
    ]
