# Generated by Django 2.0.7 on 2019-02-23 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planting', '0003_auto_20190223_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Yards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'yard',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='plant',
            name='imgURL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yards',
            name='plant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planting.Plant'),
        ),
        migrations.AddField(
            model_name='yards',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planting.User'),
        ),
    ]
